    "assert most_similar(data,'Krabi') == Nong Bua Lamphu",
    "assert most_similar(data,'Bangkok') == Khon Kaen",
    "assert most_similar(data,'Kanchanaburi') == Phang Nga",
    "assert most_similar(data,'Kalasin') == Phitsanulok",
    "assert most_similar(data,'Kamphaeng Phet') == Nakhon Pathom",
    "assert most_similar(data,'Khon Kaen') == Ratchaburi",
    "assert most_similar(data,'Chanthaburi') == Rayong",
    "assert most_similar(data,'Chachoengsao') == Prachuap Khiri Khan",
    "assert most_similar(data,'Chonburi') == Phuket",
    "assert most_similar(data,'Chai Nat') == Sakon Nakhon",
    "assert most_similar(data,'Chaiyaphum') == Nonthaburi",
    "assert most_similar(data,'Chumphon') == Samut Songkhram",
    "assert most_similar(data,'Trang') == Songkhla",
    "assert most_similar(data,'Trat') == Saraburi",
    "assert most_similar(data,'Tak') == Samut Sakhon",
    "assert most_similar(data,'Nakhon Nayok') == Trat",
    "assert most_similar(data,'Nakhon Pathom') == Kamphaeng Phet",
    "assert most_similar(data,'Nakhon Phanom') == Phitsanulok",
    "assert most_similar(data,'Nakhon Ratchasima') == Nakhon Si Thammarat",
    "assert most_similar(data,'Nakhon Si Thammarat') == Trang",
    "assert most_similar(data,'Nakhon Sawan') == Kalasin",
    "assert most_similar(data,'Nonthaburi') == Sing Buri",
    "assert most_similar(data,'Narathiwat') == Chaiyaphum",
    "assert most_similar(data,'Nan') == Uthai Thani",
    "assert most_similar(data,'Bueng Kan') == Nonthaburi",
    "assert most_similar(data,'Buriram') == Lopburi",
    "assert most_similar(data,'Pathum Thani') == Rayong",
    "assert most_similar(data,'Prachuap Khiri Khan') == Chachoengsao",
    "assert most_similar(data,'Prachinburi') == Chachoengsao",
    "assert most_similar(data,'Pattani') == Kanchanaburi",
    "assert most_similar(data,'Phra Nakhon Si Ayutthaya') == Phetchaburi",
    "assert most_similar(data,'Phayao') == Phrae",
    "assert most_similar(data,'Phang Nga') == Kanchanaburi",
    "assert most_similar(data,'Phatthalung') == Chiang Rai",
    "assert most_similar(data,'Phichit') == Phang Nga",
    "assert most_similar(data,'Phitsanulok') == Kalasin",
    "assert most_similar(data,'Phuket') == Nakhon Pathom",
    "assert most_similar(data,'Maha Sarakham') == Sakon Nakhon",
    "assert most_similar(data,'Mukdahan') == Amnat Charoen",
    "assert most_similar(data,'Yala') == Nakhon Sawan",
    "assert most_similar(data,'Yasothon') == Amnat Charoen",
    "assert most_similar(data,'Ranong') == Satun",
    "assert most_similar(data,'Rayong') == Chanthaburi",
    "assert most_similar(data,'Ratchaburi') == Khon Kaen",
    "assert most_similar(data,'Roi Et') == Chiang Mai",
    "assert most_similar(data,'Lopburi') == Buriram",
    "assert most_similar(data,'Lampang') == Ranong",
    "assert most_similar(data,'Lamphun') == Phetchaburi",
    "assert most_similar(data,'Sisaket') == Ranong",
    "assert most_similar(data,'Sakon Nakhon') == Maha Sarakham",
    "assert most_similar(data,'Songkhla') == Sisaket",
    "assert most_similar(data,'Satun') == Ranong",
    "assert most_similar(data,'Samut Prakan') == Pathum Thani",
    "assert most_similar(data,'Samut Songkhram') == Phetchabun",
    "assert most_similar(data,'Samut Sakhon') == Tak",
    "assert most_similar(data,'Saraburi') == Trat",
    "assert most_similar(data,'Sa Kaeo') == Bangkok",
    "assert most_similar(data,'Sing Buri') == Songkhla",
    "assert most_similar(data,'Suphan Buri') == Ubon Ratchathani",
    "assert most_similar(data,'Surat Thani') == Phra Nakhon Si Ayutthaya",
    "assert most_similar(data,'Surin') == Krabi",
    "assert most_similar(data,'Sukhothai') == Prachinburi",
    "assert most_similar(data,'Nong Khai') == Trang",
    "assert most_similar(data,'Nong Bua Lamphu') == Krabi",
    "assert most_similar(data,'Amnat Charoen') == Mukdahan",
    "assert most_similar(data,'Udon Thani') == Maha Sarakham",
    "assert most_similar(data,'Uttaradit') == Nakhon Sawan",
    "assert most_similar(data,'Uthai Thani') == Nan",
    "assert most_similar(data,'Ubon Ratchathani') == Phetchabun",
    "assert most_similar(data,'Ang Thong') == Saraburi",
    "assert most_similar(data,'Chiang Rai') == Lampang",
    "assert most_similar(data,'Chiang Mai') == Ratchaburi",
    "assert most_similar(data,'Phetchaburi') == Lamphun",
    "assert most_similar(data,'Phetchabun') == Ubon Ratchathani",
    "assert most_similar(data,'Loei') == Prachinburi",
    "assert most_similar(data,'Phrae') == Phayao",
    "assert most_similar(data,'Mae Hong Son') == Nakhon Sawan",
